root = "."
testdata_dir = "testdata"
.build/.server_dir = ".build/.server"

[build]
  args_bin = []
  bin = "./.build/.server/development.exe"
  cmd = "go build -o ./.build/.server/development.exe ."
  delay = 0
  exclude_dir = ["assets", ".build/.server", "vendor", "testdata", "node_modules", "vue", "api", ".vscode", ".git"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", ".build/.server", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
